[tool.poetry]
name = "todo-api"
version = "0.1.0"
description = ""
authors = ["Mateus Soares"]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^1.1.2"
Flask-PyMongo = "^2.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
